version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-aspnetcore-runtime
    working_directory: ~/NetworkListFix
    steps:
      - checkout
      - run: dotnet build
     
      
      